In [1]:
import numpy as np

In [2]:
A = np.random.randn(2,  3, 5)

In [3]:
B = A[:,::-1,...]

In [4]:
B

array([[[-0.79604888,  0.42679016,  0.84518503,  0.61907425,
          0.53842677],
        [-0.4915734 , -0.72411507, -1.44232187,  0.19382071,
         -0.83160531],
        [ 1.66422622, -0.18101241, -0.0464675 , -0.38344116,
         -0.38931189]],

       [[ 0.12828921, -0.08248162, -0.6993718 ,  0.37803428,
          0.05601799],
        [-1.02959087,  1.13462542, -0.51883609, -0.34111898,
         -1.88326665],
        [ 0.63052072,  0.13921039, -1.11604531, -0.20276004,
          0.59844247]]])

In [5]:
A

array([[[ 1.66422622, -0.18101241, -0.0464675 , -0.38344116,
         -0.38931189],
        [-0.4915734 , -0.72411507, -1.44232187,  0.19382071,
         -0.83160531],
        [-0.79604888,  0.42679016,  0.84518503,  0.61907425,
          0.53842677]],

       [[ 0.63052072,  0.13921039, -1.11604531, -0.20276004,
          0.59844247],
        [-1.02959087,  1.13462542, -0.51883609, -0.34111898,
         -1.88326665],
        [ 0.12828921, -0.08248162, -0.6993718 ,  0.37803428,
          0.05601799]]])

In [6]:
C = A[:,::-1,:]

In [8]:
C.shape

(2, 3, 5)

In [9]:
B.shape

(2, 3, 5)

In [10]:
C

array([[[-0.79604888,  0.42679016,  0.84518503,  0.61907425,
          0.53842677],
        [-0.4915734 , -0.72411507, -1.44232187,  0.19382071,
         -0.83160531],
        [ 1.66422622, -0.18101241, -0.0464675 , -0.38344116,
         -0.38931189]],

       [[ 0.12828921, -0.08248162, -0.6993718 ,  0.37803428,
          0.05601799],
        [-1.02959087,  1.13462542, -0.51883609, -0.34111898,
         -1.88326665],
        [ 0.63052072,  0.13921039, -1.11604531, -0.20276004,
          0.59844247]]])

In [11]:
np.all(B == C)

True

In [14]:
A[:]

array([[[ 1.66422622, -0.18101241, -0.0464675 , -0.38344116,
         -0.38931189],
        [-0.4915734 , -0.72411507, -1.44232187,  0.19382071,
         -0.83160531],
        [-0.79604888,  0.42679016,  0.84518503,  0.61907425,
          0.53842677]],

       [[ 0.63052072,  0.13921039, -1.11604531, -0.20276004,
          0.59844247],
        [-1.02959087,  1.13462542, -0.51883609, -0.34111898,
         -1.88326665],
        [ 0.12828921, -0.08248162, -0.6993718 ,  0.37803428,
          0.05601799]]])